<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddGurume4 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
        
        DB::table('events')->insert([
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '17',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '18',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '19',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '20',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '21',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '22',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '23',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '24',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '25',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'Fight!～FOOD×ENTERTAINMENT BATTLE',
          'eventdate' => '26',
          'time' => '10:00~19:00',
          'prefecture' => '東京',
          'place' => 'シンボルプロムナード公園',
          'genre' => 'グルメ',
          'description' => 'グルメ", "繊細なアートとコラボした日本食など、食とエンターテインメントが楽しめるグルメフェスです。8月26日まで開催予定。',
          'price' => '-',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'クラフトビアフェスティバル',
          'eventdate' => '11',
          'time' => '11:00~16:00',
          'prefecture' => '東京',
          'place' => 'すみだリバーサイドホール',
          'genre' => 'グルメ',
          'description' => '日本全国のクラフトビールを飲み比べできるビール祭り！！8月12日まで開催予定。',
          'price' => '3900円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'クラフトビアフェスティバル',
          'eventdate' => '12',
          'time' => '11:00~16:00',
          'prefecture' => '東京',
          'place' => 'すみだリバーサイドホール',
          'genre' => 'グルメ',
          'description' => '日本全国のクラフトビールを飲み比べできるビール祭り！！8月12日まで開催予定。',
          'price' => '3900円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'オーガニックワイン連続講座',
          'eventdate' => '7',
          'time' => '19:00~20:00',
          'prefecture' => '東京',
          'place' => 'マヴィ赤坂本店',
          'genre' => 'グルメ',
          'description' => '月に１度開催されているワイン講習会です。ヨーロッパ各地のオーガニックワイン産地を、実際に味わいながら学んでみませんか？',
          'price' => '3000円(1回分)',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
         [
          'name' => 'The 乾麺グランプリ 2018',
          'eventdate' => '18',
          'time' => '10:00~18:00',
          'prefecture' => '東京',
          'place' => '日比谷公園',
          'genre' => 'グルメ',
          'description' => '乾麺を使ったメニューが集結！美味しかった麺メニューにシールで投票し、二日間のシールの投票数により、グランプリを決定するイベントです。8月19日まで開催予定。',
          'price' => '食券1枚400円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'The 乾麺グランプリ 2018',
          'eventdate' => '19',
          'time' => '10:00~18:00',
          'prefecture' => '東京',
          'place' => '日比谷公園',
          'genre' => 'グルメ',
          'description' => '乾麺を使ったメニューが集結！美味しかった麺メニューにシールで投票し、二日間のシールの投票数により、グランプリを決定するイベントです。8月19日まで開催予定。',
          'price' => '食券1枚400円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '4',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '5',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '11',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '12',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '18',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '19',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '25',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ルーヴルスイーツブッフェ',
          'eventdate' => '26',
          'time' => '15:00~17:00',
          'prefecture' => '東京',
          'place' => 'コンラッド東京',
          'genre' => 'グルメ',
          'description' => '「夏のパリ」をテーマにした爽やかな味わいのフレンチスイーツや軽食が揃うブッフェ。 ルーブル美術展とコラボをし、カヌレやマロンなど、パリで有名なスイーツを楽しめます。8月の毎週末開催予定。',
          'price' => '4500円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
     ]);  
      
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
    }
}
