<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class DeleteAten extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
        
        DB::table('events')->where('name', '=', 'デザインあ展 in TOKYO')->delete();
        DB::table('events')->where('prefecture', '=', '全国')->update(['place' => '映画館']);
        
        DB::table('events')->insert([
        [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '1',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
          [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '2',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
          
          [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '3',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '4',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '5',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '6',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '7',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '8',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '9',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '10',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '11',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '12',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '13',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '14',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '15',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '16',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '17',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '18',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '19',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '20',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '21',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '22',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '23',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '24',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '25',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '26',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],  [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '27',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ], [
           'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '28',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
          [
          'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '29',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
           'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '30',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
           'name' => 'デザインあ展 in TOKYO',
          'eventdate' => '31',
          'time' => '10:00~17:00',
          'prefecture' => '東京',
          'place' => '日本未来科学館',
          'genre' => '芸術',
          'description' => 'デザイン的思考をテーマに制作されたテレビ番組についての展示　7月19日から10月18日まで展示',
          'price' => '1600円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
    }
}
