<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddSport1 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
        
        DB::table('events')->insert([
        [
          'name' => '西武‐日本ハム',
          'eventdate' => '4',
          'time' => '18:00',
          'prefecture' => '埼玉',
          'place' => 'メットライフドーム',
          'genre' => 'スポーツ',
          'description' => '「獅子風流（ししぶる）」ユニフォームを来場者全員に配布。歌手の渡辺美里さんが来場！',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '11',
        ],
        [
          'name' => '西武‐日本ハム',
          'eventdate' => '17',
          'time' => '18:00',
          'prefecture' => '埼玉',
          'place' => 'メットライフドーム',
          'genre' => 'スポーツ',
          'description' => 'ビール半額デー',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '11',
        ],
        [
          'name' => '西武‐日本ハム',
          'eventdate' => '18',
          'time' => '18:00',
          'prefecture' => '埼玉',
          'place' => 'メットライフドーム',
          'genre' => 'スポーツ',
          'description' => '親子ヒーロープロジェクト：インクレディブル・ファミリーとのコラボイベント。インクレディブル風アイマスクを来場者全員に、ピクサー公認イラストのオリジナルクリアファイルを先着10,000名に配布。また、来場の小学生以下全員にライオンズ特別仕様のボードゲーム“ポンジャン”を配布！',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '11',
        ],
        [
          'name' => '西武‐楽天',
          'eventdate' => '28',
          'time' => '18:00',
          'prefecture' => '群馬',
          'place' => '前橋球場',
          'genre' => 'スポーツ',
          'description' => '来場者には群馬開催記念の「高橋光成投手プロヂュースオリジナルTシャツ」を配布！',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '10',
        ],
        [
          'name' => 'ソフトバンク-西武',
          'eventdate' => '26',
          'time' => '13:00',
          'prefecture' => '福岡',
          'place' => 'ヤフオクドーム',
          'genre' => 'スポーツ',
          'description' => '第4弾レジェンドデー：「斉藤和巳」氏と「フリオ・ズレータ」氏によるトークショー、試合開始前のメモリアルピッチが行われる。選手たちは記念ユニホームを着用して試合に臨む。',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '40',
        ],
        [
          'name' => 'ロッテ‐ソフトバンク',
          'eventdate' => '7',
          'time' => '18:00',
          'prefecture' => '千葉',
          'place' => 'ZOZOマリンスタジアム',
          'genre' => 'スポーツ',
          'description' => '先着5000名　「クーリッシュ」プレゼント',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '12',
        ],
        [
          'name' => 'ロッテ-西武',
          'eventdate' => '21',
          'time' => '18:30',
          'prefecture' => '東京',
          'place' => '東京ドーム',
          'genre' => 'スポーツ',
          'description' => '来場者全員にLOTTE50thピンストライプユニフォーム配布',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'ソフトバンク-西武',
          'eventdate' => '12',
          'time' => '13:00',
          'prefecture' => '福岡',
          'place' => 'ヤフオクドーム',
          'genre' => 'スポーツ',
          'description' => 'SoftBankHAWKSトークショー「ロッカールーム」　試合終了後に内川選手によるトークショーが行われる。',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '40',
        ],
        [
          'name' => 'ロッテ-オリックス',
          'eventdate' => '26',
          'time' => '18:00',
          'prefecture' => '千葉',
          'place' => 'ZOZOマリンスタジアム',
          'genre' => 'スポーツ',
          'description' => 'マリンフェスタ　来場者先着20000名にマリンフェスタグッズ（LEDバッジ）が配布される。試合終了後には1000発の花火が打ち上げられる。',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '12',
        ],
        [
          'name' => 'オリックス‐西武',
          'eventdate' => '7',
          'time' => '18:00',
          'prefecture' => '大阪',
          'place' => '京セラドーム大阪',
          'genre' => 'スポーツ',
          'description' => 'Bs夏の陣',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '27',
        ],
        [
          'name' => 'オリックス‐西武',
          'eventdate' => '8',
          'time' => '18:00',
          'prefecture' => '大阪',
          'place' => '京セラドーム大阪',
          'genre' => 'スポーツ',
          'description' => 'Bs夏の陣',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '27',
        ],
        [
          'name' => 'オリックス‐西武',
          'eventdate' => '9',
          'time' => '18:00',
          'prefecture' => '大阪',
          'place' => '京セラドーム大阪',
          'genre' => 'スポーツ',
          'description' => 'Bs夏の陣',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '27',
        ],
        [
          'name' => 'オリックス‐ロッテ',
          'eventdate' => '10',
          'time' => '18:00',
          'prefecture' => '大阪',
          'place' => '京セラドーム大阪',
          'genre' => 'スポーツ',
          'description' => 'Bs夏の陣',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '27',
        ],
        [
          'name' => 'オリックス‐ロッテ',
          'eventdate' => '11',
          'time' => '14:00',
          'prefecture' => '大阪',
          'place' => '京セラドーム大阪',
          'genre' => 'スポーツ',
          'description' => 'Bs夏の陣',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '27',
        ],
        [
          'name' => 'オリックス‐ロッテ',
          'eventdate' => '12',
          'time' => '13:00',
          'prefecture' => '大阪',
          'place' => '京セラドーム大阪',
          'genre' => 'スポーツ',
          'description' => 'Bs夏の陣',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '27',
        ],
        [
          'name' => '日本ハム‐ソフトバンク',
          'eventdate' => '22',
          'time' => '18:00',
          'prefecture' => '東京',
          'place' => '東京ドーム',
          'genre' => 'スポーツ',
          'description' => '15歳以下のこども先着5000名様に北海道スカイブルージュニアキャッププレゼント',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '13',
        ],
        [
          'name' => '日本ハム‐ソフトバンク',
          'eventdate' => '23',
          'time' => '18:00',
          'prefecture' => '東京',
          'place' => '東京ドーム',
          'genre' => 'スポーツ',
          'description' => '15歳以下のこども先着5000名様に北海道スカイブルージュニアキャッププレゼント',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '13',
        ],
        [
          'name' => '日本ハム-楽天',
          'eventdate' => '24',
          'time' => '18:00',
          'prefecture' => '北海道',
          'place' => '札幌ドーム',
          'genre' => 'スポーツ',
          'description' => 'ビール半額デー',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '1',
        ],
        [
          'name' => '日本ハム-楽天',
          'eventdate' => '25',
          'time' => '15:00',
          'prefecture' => '北海道',
          'place' => '札幌ドーム',
          'genre' => 'スポーツ',
          'description' => 'ファイターズ花火大会:試合終了後に3000発の花火を打ち上げる。15歳以下のこども先着5000名様に北海道スカイブルージュニアキャッププレゼント',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '1',
        ],
        [
          'name' => '日本ハム-楽天',
          'eventdate' => '26',
          'time' => '14:00',
          'prefecture' => '北海道',
          'place' => '札幌ドーム',
          'genre' => 'スポーツ',
          'description' => '来場者全員に北海道スカイブルーユニフォームプレゼント',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '1',
        ],
        [
          'name' => '楽天-ロッテ',
          'eventdate' => '19',
          'time' => '17:00',
          'prefecture' => '宮城',
          'place' => '楽天生命パーク',
          'genre' => 'スポーツ',
          'description' => '来場の小学6年生以下のお子様全員にキッズキャップをプレゼント',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '4',
        ],
        [
          'name' => '楽天-ロッテ',
          'eventdate' => '3',
          'time' => '18:00',
          'prefecture' => '宮城',
          'place' => '楽天生命パーク',
          'genre' => 'スポーツ',
          'description' => 'ビール半額デー',
          'price' => '公式サイト参照',
          'genrenum' => '5',
          'prefecturenum' => '4',
        ],
      ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
    }
}
