<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddGurume3 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
        
        DB::table('events')->insert([
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '1',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '2',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '3',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '4',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '5',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '6',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '7',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '8',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '9',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '10',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '11',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '12',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '13',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '14',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '15',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '16',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '17',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '18',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '19',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '20',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '21',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '22',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '23',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '24',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '25',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '26',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '27',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '28',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '29',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '30',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
        [
          'name' => 'マーメイドと楽しむスイーツブッフェ',
          'eventdate' => '31',
          'time' => '15:00~17:30',
          'prefecture' => '東京',
          'place' => '京王プラザホテル',
          'genre' => 'グルメ',
          'description' => '童話「人魚姫」をテーマに、マーメイドの世界を表現したカラフルなスイーツが堪能できます。9月30日まで開催予定。',
          'price' => '3800円',
          'genrenum' => '4',
          'prefecturenum' => '13',
        ],
     ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
    }
}
