<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddGeijutsu2 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
        
        DB::table('events')->insert([
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '1',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '2',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '3',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '4',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '5',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '6',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '7',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '8',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '9',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '10',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '11',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '12',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '13',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
         [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '14',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '15',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '16',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '17',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '18',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '19',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '20',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '21',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '22',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '23',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '24',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '25',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '26',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '27',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '28',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '29',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '30',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
        [
          'name' => '没後50年　藤田嗣治展',
          'eventdate' => '31',
          'time' => '9:30~17:30',
          'prefecture' => '東京',
          'place' => '東京都美術館',
          'genre' => '芸術',
          'description' => '現代においても広く愛される藤田嗣治の作品を数多く展示。7月31日~10月8日まで開催',
          'price' => '1400円',
          'genrenum' => '6',
          'prefecturenum' => '13',
        ],
       ]);
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('events', function (Blueprint $table) {
            //
        });
    }
}
